CRUD/urls.py
# from django.shortcuts import redirect
from django.urls import path ,include
from . import views

urlpatterns = [
    path('', views.index,name='index'),
    path('display', views.student_dispay,name='student_display'),
    path('del', views.student_delete,name='student_delete'),
    path('form', views.student_form,name='student_form'),
    path('delete/<str:roll_number>', views.student_delete,name='student_delete'),

    path('form/<str:roll_number>', views.student_form,name='student_update'),

]

Project/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('CRUD.urls'))    
]

CRUD/models.py
from django.db import models

class Department(models.Model):
    se = 'Software Engineering'
    cs = 'Computer Science'

    DEPARTMENTS = (
        ('se' , se),
        ('cs' ,cs)

    )

    # id = models.AutoField(max_length=2,default=se,choices=DEPARTMENTS)
    name = models.CharField(max_length=20)


    def __str__(self):
        return self.name
        


class Student(models.Model):
    SECTIONS = (
        ['A','A'],
        ['B','B'],
        ['C','C']
        )
    
    roll_number = models.CharField(max_length=20,unique=True,primary_key=True)
    name = models.CharField(max_length=20)
    section = models.CharField(max_length=1,choices=SECTIONS,default='A')
    department = models.ForeignKey(Department,on_delete=models.CASCADE)

    def __str__(self):
        return self.roll_number

        

CRUD/forms.py
from django import forms
from .models import Student

class StudentForm(forms.ModelForm):
    
    class Meta:
        
        model = Student
        fields  = "__all__"

    def __init__(self,*args,**kwargs):
        super(StudentForm,self).__init__(*args,**kwargs)
        self.fields['department'].empty_label = 'Select '

CRUD/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import templates
from .forms import StudentForm
from .models import Student

# Create your views here.
def index(request):
    print("Request Object :" , request.content_type)
    return redirect("/display")

def student_dispay(request):
    context = {'student_data':Student.objects.all()}
    return render(request,'CRUD/display.html',context)

# Will be used for insert and update 
def student_form(request,roll_number = None):
    form = StudentForm

    if request.method == 'GET':
        if roll_number is  not None:
            student = Student.objects.get(pk=roll_number)
            form = StudentForm(instance=student)
        
        return render(request,'CRUD/form.html',{'form':form})
    else:
        if roll_number is None:
            form = form(request.POST)
        else:
            student = Student.objects.get(pk=roll_number)
            form = StudentForm(request.POST,instance= student)

        if form.is_valid():
            form.save()
        return redirect('/display')

def student_delete(request,roll_number = None):

    student = Student.objects.get(pk=roll_number)
    student.delete()
    return redirect('/display')

CRUD/templates/CRUD/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


    <title>Students</title>
</head>
<body>
    <div class="container" style="margin-top: 10rem;">
        <div class="col-md-10 offset-md-1 mt-6">
            <div class="jumbotron">
                <h1 class="display-4">Simple CRUD APP</h1>
                <p class="lead"></p>
                <hr class="my-4">
                <!-- <p>It uses utility classes for typography and spacing to space content out within the larger container.</p> -->
                <p class="lead">
                  <!-- <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a> -->
                </p>
                {% block main %}
        
                {% endblock main %}   


              </div>
                 
        </div>
    
       
    </div>
    
    
        
</body>
</html>

CRUD/templates/CRUD/display.html
{% extends 'CRUD/base.html' %}


{% block main %}

<!-- <h1>Student Table  </h1> -->
<table class="table table-borderless">
    <thead>
    <tr>
        <td>Roll Number</td>
        <td>Name</td>
        <td>Section</td>
        <td>Department</td>
        <td>Actions</td>
        <td> 
            <a name="" id="" class="btn btn-primary" href="{% url 'student_form' %} " role="button">Add Student
            <i class="fa fa-plus-circle" aria-hidden="true"></i>
            </a> 
        </td>

    </tr>
</thead>
<tbody>
    {% for student in student_data %}
    <tr>
        <td> {{student.roll_number}}</td>
        <td>{{student.name}}</td>
        <td>{{student.section}}</td>
        <td>{{student.department}}</td>
        <td>
            <a href="{% url 'student_update' student.roll_number %}" class="btn text-secondary px-8 float-left ">
                <i class="fa fa-edit fa-lg"></i>
            </a>
            <form action="{% url 'student_delete' student.roll_number %}" method="post" class="d-inline px-8 float-left">
                {% csrf_token %}
                <button type="submit"  class="btn text-secondary px-8 float-right" >
                    <i class="fa fa-trash fa-lg"></i> 
                </button>
            </form>
        </td>
    </tr>
        
    {% endfor %}
        


</tbody>


</table>    
{% endblock main %}
    

CRUD/templates/CRUD/form.html
{% extends 'CRUD/base.html' %}

{% block main %}

<style>
    #id_roll_number,#id_name,#id_section,#id_department {width: 100%;}
</style>

<h1>Student Forms</h1>

{% load crispy_forms_tags %}
<form action="" method="post" autocomplete="on">

    {% csrf_token %}
    <!-- {{form|crispy}} -->
    {{form.roll_number|as_crispy_field}}
    {{form.name|as_crispy_field}}
    <div class="row">
        <div class="col-md-4">
            {{form.section|as_crispy_field}}
        </div>
        <div class="col-md-8">
            {{form.department|as_crispy_field}}

        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <button type="submit" class="btn btn-success btn-block btn-lg mt-5">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
    
                Submit
            </button>
        </div>
        <div class="col-md-4">
            <a type="button" href='{% url "student_display" %}' class="btn btn-secondary btn-lg mt-5">
                <!-- <i class="fa fa-stream"></i> -->
                <i class="fa fa-list" aria-hidden="true"></i>
                 Student Data

            </a>
        </div>
    </div>
</form>


    
{% endblock main %}
    